apiVersion: v1
kind: Service
metadata:
  name: trow-30999
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: http
      nodePort: 30999
  selector:
    app.kubernetes.io/instance: trow
    app.kubernetes.io/name: trow
  type: NodePort
